// Code generated by "stringer -type JobStatus ."; DO NOT EDIT.

package blero

import "strconv"

const _JobStatus_name = "pendinginprogresscompletefailed"

var _JobStatus_index = [...]uint8{0, 7, 17, 25, 31}

func (i JobStatus) String() string {
	if i >= JobStatus(len(_JobStatus_index)-1) {
		return "JobStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _JobStatus_name[_JobStatus_index[i]:_JobStatus_index[i+1]]
}
